<a href="https://colab.research.google.com/github/pipal2004/task1_python_Prerequisite/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task1

Array creation (array, arange, linspace, zeros, ones, eye)


In [ ]:
import numpy as np
arr=np.array([1,3,5,2,1,6,0])
print("array():",arr)
r = np.arange(1, 7, 2)
print("arange():",r)
l= np.linspace(0, 20, 5)
print("linspace():",l)
z= np.zeros((3, 2))
print("zeros():\n", z)
o=np.ones((3,3))
print("ones():\n",o)
e=np.eye(5)
print("eye():\n",e)

array(): [1 3 5 2 1 6 0]
arange(): [1 3 5]
linspace(): [ 0.  5. 10. 15. 20.]
zeros():
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
ones():
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
eye():
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Indexing and slicing


In [ ]:
import numpy as np
#INDEXING
#1D array
array1=np.array([23,44,54,69,73,20])
print(array1)
print("Element at index 2 is:",array1[2])
print("Last element of array :", array1[-1])
#2D array
array2=np.array([[1,2,3],[9,4,6],[4,4,0]])
print(array2)
print("Element at row=2 and column=1 is:",array2[2,1])
print("entire column 1:",array2[:,1])
print("Entire row2:",array2[2])
#SLICING
#1D array
print(array1[0:5:2])
print("first 3 elements:",array1[:3])
print("every second element:",array1[::2])
print("Last 3 elements:", array1[-3:])
#2Darray
print("elements from row=0 to col=1:\n",array2[0:2, 1:3])
print("elements of all rows and every 2nd column:\n",array2[:, ::2])
print("all columns, every 2nd row:\n",array2[::2,:])

[23 44 54 69 73 20]
Element at index 2 is: 54
Last element of array : 20
[[1 2 3]
 [9 4 6]
 [4 4 0]]
Element at row=2 and column=1 is: 4
entire column 1: [2 4 4]
Entire row2: [4 4 0]
[23 54 73]
first 3 elements: [23 44 54]
every second element: [23 54 73]
Last 3 elements: [69 73 20]
elements from row=0 to col=1:
 [[2 3]
 [4 6]]
elements of all rows and every 2nd column:
 [[1 3]
 [9 6]
 [4 0]]
all columns, every 2nd row:
 [[1 2 3]
 [4 4 0]]


Shape manipulation (reshape, flatten, transpose)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr)

# Reshape to 2 rows, 3 columns
arr_reshaped = arr.reshape(2, 3)
print("Reshaped array (2x3):\n", arr_reshaped)
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
#flatten()
flat_arr = arr2d.flatten()
print("Flattened array:", flat_arr)

#transpose()
arr_transpose = arr2d.transpose()
print("Original array:\n", arr2d)
print("Transposed array:\n", arr_transpose)



Original array: [1 2 3 4 5 6]
Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
Flattened array: [1 2 3 4 5 6]
Original array:
 [[1 2 3]
 [4 5 6]]
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]


Math ops (mean, std, sum, dot, matmul)



In [ ]:
import numpy as np
array=np.array([[1,2],[3,4]])
print(array)
#mean
print("Mean of all elements:\n",np.mean(array))
print("Mean along columns\n",np.mean(array, axis=0))
print("Mean along rows:\n",np.mean(array, axis=1))

#sum
print("sum of all elements:\n",np.sum(array))
print("sum along columns:\n",np.sum(array,axis=0))
print("sum along rows:\n",np.sum(array,axis=1))

#std
print(np.std(array))

#dot
x=np.array([2,3])
y=np.array([4,5])
print(np.dot(x,y))

#matmul
A = np.array([[3, 2], [3, 1]])
B = np.array([[5, 7], [2, 9]])
print("Using matmul:\n",np.matmul(A, B))
print("Using @ operator:\n",A @ B)

[[1 2]
 [3 4]]
Mean of all elements:
 2.5
Mean along columns
 [2. 3.]
Mean along rows:
 [1.5 3.5]
sum of all elements:
 10
sum along columns:
 [4 6]
sum along rows:
 [3 7]
1.118033988749895
23
Using matmul:
 [[19 39]
 [17 30]]
Using @ operator:
 [[19 39]
 [17 30]]


Random module (rand, randn, randint, choice)


In [ ]:
import numpy as np

print("rand(3):", np.random.rand(3))
print("rand(2, 3):\n", np.random.rand(2, 3))

print("randn(3):", np.random.randn(3))
print("randn(2, 3):\n", np.random.randn(2, 3))

print("randint:", np.random.randint(1, 10))
print("randint array:", np.random.randint(1, 10, size=(2, 3)))

arr = np.array([10, 20, 30, 40, 50])
print("choice single:", np.random.choice(arr))
print("choice multiple:", np.random.choice(arr, size=3))
print("choice with replacement:", np.random.choice(arr, size=3, replace=True))
print("choice without replacement:", np.random.choice(arr, size=3, replace=False))


rand(3): [0.86240648 0.51332866 0.17683698]
rand(2, 3):
 [[0.93130088 0.55163364 0.17923929]
 [0.07717853 0.4677929  0.25818243]]
randn(3): [ 1.01303862  0.34277699 -0.67713747]
randn(2, 3):
 [[ 0.59617545 -0.47835531 -0.28631195]
 [ 0.40839203 -0.41122184 -0.66545498]]
randint: 6
randint array: [[9 2 4]
 [4 5 2]]
choice single: 20
choice multiple: [40 30 20]
choice with replacement: [10 30 20]
choice without replacement: [30 10 40]
